### ISSUE TITLE
Code128 Barcodes

### ISSUE THREAD

**Issue by Jack-Chronicle** [Kingal1337/flipper-barcode-generator#10] opened 2024-03-10 13:57 UTC
Trying to set up some code128 barcodes, specifically barcodes that change the settings for my scanner, but I keep getting an encoding error when I try to load them on the Flipper
And if I try something else for the data, just random numbers or anything, it doesn't scan. Even if it works with the original

**Comment by Kingal1337** [comment] 2024-03-10 19:14
Can you post a picture of the barcode?

**Comment by Jack-Chronicle** [comment] 2024-03-11 00:05
Trying to set up Barcodes line this one
![PXL_20240311_000440225.jpg](https://github.com/Kingal1337/flipper-barcode-generator/assets/18507378/d2243671-5558-4b09-b543-f8882716a3b0)

**Comment by Kingal1337** [comment] 2024-03-11 01:34
I have found the issue, the issue is the hashtag symbol. In the encoding tables the hashtag is store as `#: 03` and hashtags are ignore because they represent comments. So when the program tries to look for the hashtag encoding it fails.

it will be fixed in the next release, which should come out in the next day or two.

**Closed as completed by Kingal1337** 2024-03-11 01:34 UTC
